package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/UNKNOWN.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Monday, November 5, 2012 3:41:55 AM WET
*/

public interface UNKNOWN
{

  /**
     * XXX
     */
  public static final short value = (short)(5);
}
