package org.jboss.com.sun.corba.se.spi.activation;


/**
* org.jboss.com.sun.corba/se/spi/activation/IIOP_CLEAR_TEXT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org.jboss.com.sun.corba/se/spi/activation/activation.idl
* Monday, November 5, 2012 3:44:52 AM WET
*/

public interface IIOP_CLEAR_TEXT
{

  // to avoid a compilation dependency.
  public static final String value = "IIOP_CLEAR_TEXT";
}
