package org.jboss.com.sun.corba.se.spi.activation;


/**
* org.jboss.com.sun.corba/se/spi/activation/RepositoryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org.jboss.com.sun.corba/se/spi/activation/activation.idl
* Monday, November 5, 2012 3:44:53 AM WET
*/

public interface RepositoryOperations 
{

  // always uninstalled.
  int registerServer (org.jboss.com.sun.corba.se.spi.activation.RepositoryPackage.ServerDef serverDef) throws org.jboss.com.sun.corba.se.spi.activation.ServerAlreadyRegistered, org.jboss.com.sun.corba.se.spi.activation.BadServerDefinition;

  // unregister server definition
  void unregisterServer (int serverId) throws org.jboss.com.sun.corba.se.spi.activation.ServerNotRegistered;

  // get server definition
  org.jboss.com.sun.corba.se.spi.activation.RepositoryPackage.ServerDef getServer (int serverId) throws org.jboss.com.sun.corba.se.spi.activation.ServerNotRegistered;

  // Return whether the server has been installed
  boolean isInstalled (int serverId) throws org.jboss.com.sun.corba.se.spi.activation.ServerNotRegistered;

  // if the server is currently marked as installed.
  void install (int serverId) throws org.jboss.com.sun.corba.se.spi.activation.ServerNotRegistered, org.jboss.com.sun.corba.se.spi.activation.ServerAlreadyInstalled;

  // if the server is currently marked as uninstalled.
  void uninstall (int serverId) throws org.jboss.com.sun.corba.se.spi.activation.ServerNotRegistered, org.jboss.com.sun.corba.se.spi.activation.ServerAlreadyUninstalled;

  // list registered servers
  int[] listRegisteredServers ();

  // servers.
  String[] getApplicationNames ();

  // Find the ServerID associated with the given application name.
  int getServerID (String applicationName) throws org.jboss.com.sun.corba.se.spi.activation.ServerNotRegistered;
} // interface RepositoryOperations
