package org.jboss.com.sun.corba.se.spi.activation;


/**
* org.jboss.com.sun.corba/se/spi/activation/ActivatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org.jboss.com.sun.corba/se/spi/activation/activation.idl
* Monday, November 5, 2012 3:44:52 AM WET
*/

public interface ActivatorOperations 
{

  // A new ORB started server registers itself with the Activator
  void active (int serverId, org.jboss.com.sun.corba.se.spi.activation.Server serverObj) throws org.jboss.com.sun.corba.se.spi.activation.ServerNotRegistered;

  // Install a particular kind of endpoint
  void registerEndpoints (int serverId, String orbId, org.jboss.com.sun.corba.se.spi.activation.EndPointInfo[] endPointInfo) throws org.jboss.com.sun.corba.se.spi.activation.ServerNotRegistered, org.jboss.com.sun.corba.se.spi.activation.NoSuchEndPoint, org.jboss.com.sun.corba.se.spi.activation.ORBAlreadyRegistered;

  // list active servers
  int[] getActiveServers ();

  // If the server is not running, start it up.
  void activate (int serverId) throws org.jboss.com.sun.corba.se.spi.activation.ServerAlreadyActive, org.jboss.com.sun.corba.se.spi.activation.ServerNotRegistered, org.jboss.com.sun.corba.se.spi.activation.ServerHeldDown;

  // If the server is running, shut it down
  void shutdown (int serverId) throws org.jboss.com.sun.corba.se.spi.activation.ServerNotActive, org.jboss.com.sun.corba.se.spi.activation.ServerNotRegistered;

  // currently running, this method will activate it.
  void install (int serverId) throws org.jboss.com.sun.corba.se.spi.activation.ServerNotRegistered, org.jboss.com.sun.corba.se.spi.activation.ServerHeldDown, org.jboss.com.sun.corba.se.spi.activation.ServerAlreadyInstalled;

  // list all registered ORBs for a server
  String[] getORBNames (int serverId) throws org.jboss.com.sun.corba.se.spi.activation.ServerNotRegistered;

  // After this hook completes, the server may still be running.
  void uninstall (int serverId) throws org.jboss.com.sun.corba.se.spi.activation.ServerNotRegistered, org.jboss.com.sun.corba.se.spi.activation.ServerHeldDown, org.jboss.com.sun.corba.se.spi.activation.ServerAlreadyUninstalled;
} // interface ActivatorOperations
