package org.jboss.com.sun.corba.se.spi.activation;


/**
* org.jboss.com.sun.corba/se/spi/activation/LocatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org.jboss.com.sun.corba/se/spi/activation/activation.idl
* Monday, November 5, 2012 3:44:53 AM WET
*/

public interface LocatorOperations 
{

  // Starts the server if it is not already running.
  org.jboss.com.sun.corba.se.spi.activation.LocatorPackage.ServerLocation locateServer (int serverId, String endPoint) throws org.jboss.com.sun.corba.se.spi.activation.NoSuchEndPoint, org.jboss.com.sun.corba.se.spi.activation.ServerNotRegistered, org.jboss.com.sun.corba.se.spi.activation.ServerHeldDown;

  // Starts the server if it is not already running.
  org.jboss.com.sun.corba.se.spi.activation.LocatorPackage.ServerLocationPerORB locateServerForORB (int serverId, String orbId) throws org.jboss.com.sun.corba.se.spi.activation.InvalidORBid, org.jboss.com.sun.corba.se.spi.activation.ServerNotRegistered, org.jboss.com.sun.corba.se.spi.activation.ServerHeldDown;

  // get the port for the endpoint of the locator
  int getEndpoint (String endPointType) throws org.jboss.com.sun.corba.se.spi.activation.NoSuchEndPoint;

  // to pick a particular port type.
  int getServerPortForType (org.jboss.com.sun.corba.se.spi.activation.LocatorPackage.ServerLocationPerORB location, String endPointType) throws org.jboss.com.sun.corba.se.spi.activation.NoSuchEndPoint;
} // interface LocatorOperations
