package org.jboss.com.sun.corba.se.spi.activation;


/**
* org.jboss.com.sun.corba/se/spi/activation/ServerManager.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org.jboss.com.sun.corba/se/spi/activation/activation.idl
* Monday, November 5, 2012 3:44:53 AM WET
*/

public interface ServerManager extends ServerManagerOperations, org.jboss.com.sun.corba.se.spi.activation.Activator, org.jboss.com.sun.corba.se.spi.activation.Locator
{
} // interface ServerManager
