package org.jboss.com.sun.corba.se.PortableActivationIDL;


/**
* org.jboss.com.sun.corba/se/PortableActivationIDL/ServerProxy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org.jboss.com.sun.corba/se/PortableActivationIDL/activation.idl
* Monday, November 5, 2012 3:44:56 AM WET
*/


/** Server callback interface, passed to Activator in registerServer method.
    */
public interface ServerProxy extends ServerProxyOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerProxy
